[package]
name = "diesel_app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
diesel = { version = "2.2.10", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15.7"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
